if(FCITX5_MACOS_CATALINA_PORT)
    if(EXISTS "${CMAKE_SOURCE_DIR}/scripts/gettext-shim.py")
        set(GETTEXT_SHIM_EXECUTABLE "${CMAKE_SOURCE_DIR}/scripts/gettext-shim.py")
    else()
        set(GETTEXT_SHIM_EXECUTABLE "${PROJECT_SOURCE_DIR}/scripts/gettext-shim.py")
    endif()
    set(Gettext_FOUND TRUE)
    set(GETTEXT_FOUND TRUE)
    set(Gettext_VERSION "0.0")
    set(GETTEXT_VERSION_STRING "0.0")
    set(GETTEXT_MSGFMT_EXECUTABLE "${GETTEXT_SHIM_EXECUTABLE}" CACHE FILEPATH "Catalina gettext shim" FORCE)
    set(GETTEXT_MSGMERGE_EXECUTABLE "${GETTEXT_SHIM_EXECUTABLE}" CACHE FILEPATH "Catalina gettext shim" FORCE)
    set(GETTEXT_XGETTEXT_EXECUTABLE "${GETTEXT_SHIM_EXECUTABLE}" CACHE FILEPATH "Catalina gettext shim" FORCE)
else()
    include("${CMAKE_ROOT}/Modules/FindGettext.cmake")
endif()
